name: django

on:
  push:
    branches: [ "principal", "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # también vale "3.8", "3.9" si quieres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks
        run: |
          python manage.py check --deploy --fail-level WARNING

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: yourproject.settings
        run: |
          python -m pytest -q
